### ISSUE TITLE
Semicolon after `@charset` should be optional

### ISSUE THREAD

**Issue by Keats** [kaj/rsass#108] opened 2021-05-10 18:39 UTC
From Bulma (current master)

```
(venv) ~/C/pulls $ ./rsass/target/release/rsass bulma/bulma.sass 
Parse error: Eof
  ,
2 | /*! bulma.io v0.9.2 | MIT License | github.com/jgthms/bulma */
  | ^
  '
  bulma/bulma.sass 2:1  root stylesheet
```

**Comment by kaj** [comment] 2021-05-11 12:10
Hm.  That type of comment seems to be handled fine to me.  Maybe the problem is a comment in that position?

Ah, yes.  The problem is that there is no `;` at the end of the `@charset` declaration on line 1.  Yes, that should probably be optional.

**Comment by kaj** [comment] 2021-05-13 11:34
Looking closer, I notice that the bulma source files is in `sass` syntax, not `scss`.  Despite the name, rsass don't actually support the sass indention-based syntax (yet), only scss.  So I think I'll just close this after all.

**Comment by Keats** [comment] 2021-05-13 12:00
Whoa I didn't realise anyone was still using the sass syntax. That's a bit annoying but oh well.

**Closed** 2021-05-13 12:45 UTC
